"""One committed record of what actually stopped recent runs.

The loop's two queues were not equally legible. Unreachable affordances are
derived — `controls.cfg` gives binding parity a denominator the project cannot
edit — while observed failures lived only in `runs/<id>/events.jsonl`, which
`.gitignore` excludes and which is 2 GB of append-only evidence on one laptop.
Every agent picking up the work re-read raw bundles to reconstruct the same
list, and anything nobody re-derived was simply forgotten between sessions.

So the blockers become an artifact with the same discipline as the mutation
ledger: the committed document *is* the record, machine-local bundles are how
new evidence enters it, and regeneration on a clone with no `runs/` at all
reproduces the file byte for byte. That last property is what lets a staleness
gate exist at all — it cannot depend on the machine that ran the agent.

Two things are deliberately not done here. Nothing attributes a blocker to an
owning module: that is a judgement, and a wrong owner recorded automatically is
worse than no owner. And nothing decides a blocker is fixed; a signature simply
stops appearing in newer runs, which the `state` column reports without
claiming a cause.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

GENERATED_MARKER = (
    "<!-- generated by scripts/export_blocker_ledger.py; edits are overwritten -->"
)
LEDGER_NAME = "OBSERVED_BLOCKERS.md"

# How many of the newest run bundles one export reads. The corpus is gigabytes
# and grows every run, so a gate that scanned all of it would stop being run.
# The window bounds the *evidence*, never the record: merged rows persist after
# their runs age out of it.
DEFAULT_SCAN_LIMIT = 12

# Long enough to identify a failure, short enough to keep one row on one line.
EXAMPLE_LENGTH = 160
SIGNATURE_LENGTH = 120

_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
_COLUMNS = 6
_ABSENT = "—"

OPEN = "open"
NOT_IN_NEWEST = "not-in-newest"

# Event types that carry a reason a run stopped making progress. `run_finished`
# is deliberately absent: a final stop reason is the *last* thing that happened,
# which the loop prompt warns is not the same as the earliest causal blocker.
FAILURE_EVENTS = ("plan_step_failed", "plan_rejected", "planner_error")


def _read_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_utf8(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


@dataclass(frozen=True, slots=True)
class ObservedBlocker:
    """One failure class, and the newest evidence window that saw it."""

    signature: str
    example: str
    runs: int
    occurrences: int
    last_run_id: str
    last_seen_at: str


def normalize_timestamp(value: str) -> str:
    """Second-resolution UTC, so rendering and parsing are exact inverses."""

    return datetime.fromisoformat(value).astimezone(UTC).strftime(_TIMESTAMP_FORMAT)


def blocker_signature(reason: str) -> str:
    """Collapse one failure message into a class other runs can match.

    Two runs never fail identically: quantities, purse totals, timeouts, step
    ids and entity handles all differ. Grouping on the raw string would file
    every occurrence as its own blocker and make the ledger a transcript, so
    the varying parts are replaced rather than trusted.
    """

    collapsed = " ".join(reason.split())
    # Quoted names are step ids, item names and action kinds - the identity of
    # an instance, not of the failure.
    collapsed = re.sub(r"'[^']*'", "'*'", collapsed)
    collapsed = re.sub(r'"[^"]*"', '"*"', collapsed)
    # Handles and hex ids before digits, or their digits survive as noise.
    collapsed = re.sub(r"\b[0-9a-f]{8,}\b", "<id>", collapsed)
    collapsed = re.sub(r"\d+(?:\.\d+)?", "#", collapsed)
    return collapsed[:SIGNATURE_LENGTH].rstrip()


def _example(reason: str) -> str:
    return " ".join(reason.split())[:EXAMPLE_LENGTH].rstrip()


def blockers_from_run(path: Path) -> dict[str, tuple[str, int]]:
    """Failure signatures and their counts in one bundle, with one example each.

    Reads line by line because a bundle can be hundreds of megabytes, and skips
    unparseable lines rather than failing: a truncated final line is the normal
    state of an append-only log whose writer was interrupted.
    """

    found: dict[str, tuple[str, int]] = {}
    try:
        handle = path.open(encoding="utf-8")
    except OSError:
        return found
    with handle:
        for line in handle:
            if not any(name in line for name in FAILURE_EVENTS):
                continue
            try:
                event = json.loads(line)
            except ValueError:
                continue
            if event.get("event_type") not in FAILURE_EVENTS:
                continue
            payload = event.get("payload")
            if not isinstance(payload, dict):
                continue
            reason = payload.get("reason")
            if not isinstance(reason, str) or not reason.strip():
                continue
            signature = blocker_signature(reason)
            example, count = found.get(signature, (_example(reason), 0))
            found[signature] = (example, count + 1)
    return found


def _run_timestamp(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, UTC).strftime(_TIMESTAMP_FORMAT)


def newest_run_bundles(runs_dir: Path, limit: int = DEFAULT_SCAN_LIMIT) -> list[Path]:
    """The newest bundles that contain an event log, newest first."""

    if not runs_dir.is_dir():
        return []
    bundles = [
        child / "events.jsonl"
        for child in runs_dir.iterdir()
        if child.is_dir() and (child / "events.jsonl").is_file()
    ]
    bundles.sort(key=lambda path: (path.stat().st_mtime, path.parent.name), reverse=True)
    return bundles[:limit]


def blockers_from_runs(
    runs_dir: Path,
    limit: int = DEFAULT_SCAN_LIMIT,
) -> tuple[dict[str, ObservedBlocker], str]:
    """Scan the newest bundles. Returns the blockers and the newest run's id."""

    bundles = newest_run_bundles(runs_dir, limit)
    if not bundles:
        return {}, ""
    newest_run_id = bundles[0].parent.name
    seen: dict[str, ObservedBlocker] = {}
    # Oldest first, so the newest bundle overwrites `last_run_id` last.
    for bundle in reversed(bundles):
        run_id = bundle.parent.name
        observed_at = _run_timestamp(bundle)
        for signature, (example, count) in blockers_from_run(bundle).items():
            previous = seen.get(signature)
            if previous is None:
                seen[signature] = ObservedBlocker(
                    signature=signature,
                    example=example,
                    runs=1,
                    occurrences=count,
                    last_run_id=run_id,
                    last_seen_at=observed_at,
                )
                continue
            seen[signature] = ObservedBlocker(
                signature=signature,
                example=previous.example,
                runs=previous.runs + 1,
                occurrences=previous.occurrences + count,
                last_run_id=run_id,
                last_seen_at=observed_at,
            )
    return seen, newest_run_id


def merge_blockers(
    existing: dict[str, ObservedBlocker],
    discovered: dict[str, ObservedBlocker],
) -> dict[str, ObservedBlocker]:
    """Newer evidence replaces older wholesale; nothing is ever dropped.

    Counts describe the most recent window that saw a signature rather than a
    running total, because a total cannot be maintained without remembering
    every run already counted - and a ledger that grows by one line per run is
    a transcript, which is what this exists to replace.
    """

    merged = dict(existing)
    for signature, blocker in discovered.items():
        previous = merged.get(signature)
        if previous is None or blocker.last_seen_at >= previous.last_seen_at:
            merged[signature] = blocker
    return merged


def blocker_state(blocker: ObservedBlocker, newest_run_id: str) -> str:
    """Whether the newest recorded run still exhibited this.

    Derived from stored fields alone. Deriving it from whatever bundles happen
    to be on this machine would make the document differ between a laptop and a
    clone, and the staleness gate would then be unable to exist.
    """

    if newest_run_id and blocker.last_run_id == newest_run_id:
        return OPEN
    return NOT_IN_NEWEST


def parse_ledger(text: str) -> tuple[dict[str, ObservedBlocker], str]:
    """Read back a rendered ledger. The exact inverse of `render_ledger`."""

    blockers: dict[str, ObservedBlocker] = {}
    newest_run_id = ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("newest run  "):
            candidate = stripped.removeprefix("newest run  ").strip()
            newest_run_id = "" if candidate == _ABSENT else candidate
            continue
        if not stripped.startswith("|") or not stripped.endswith("|"):
            continue
        fields = [field.strip() for field in stripped[1:-1].split("|")]
        if len(fields) != _COLUMNS:
            continue
        signature = fields[0]
        if not signature.startswith("`") or not signature.endswith("`"):
            continue
        try:
            runs = int(fields[2])
            occurrences = int(fields[3])
        except ValueError:
            continue
        canonical_signature = signature[1:-1].rstrip()
        blocker = ObservedBlocker(
            signature=canonical_signature,
            example=fields[1],
            runs=runs,
            occurrences=occurrences,
            last_run_id=fields[4],
            last_seen_at=fields[5],
        )
        previous = blockers.get(canonical_signature)
        if previous is None or blocker.last_seen_at >= previous.last_seen_at:
            blockers[canonical_signature] = blocker
    return blockers, newest_run_id


def _escape_cell(value: str) -> str:
    """A pipe inside a reason would split the row and break the inverse."""

    return value.replace("|", "\\|")


def _open_count(blockers: dict[str, ObservedBlocker], newest_run_id: str) -> int:
    return sum(
        1
        for blocker in blockers.values()
        if blocker_state(blocker, newest_run_id) == OPEN
    )


def render_ledger(
    blockers: dict[str, ObservedBlocker],
    newest_run_id: str,
) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        "# Observed blockers",
        "",
        "What actually stopped recent runs, derived from `runs/<id>/events.jsonl`",
        "rather than from a list anyone maintains by hand. Failure messages are",
        "collapsed into signatures - quantities, ids and timeouts replaced - so",
        "repeated failures group instead of filing one row per occurrence.",
        "",
        "`open` means the newest recorded run still hit it. `not-in-newest` means",
        "it did not, which is evidence and not a claim that anything fixed it.",
        "Counts describe the window that last saw a signature, not a running",
        "total. Rows are never dropped, so a blocker that stops recurring stays",
        "visible with the run that last exhibited it.",
        "",
        "```text",
        f"newest run  {newest_run_id or _ABSENT}",
        f"signatures  {len(blockers)}",
        f"open        {_open_count(blockers, newest_run_id)}",
        "```",
        "",
        "| signature | example | runs | seen | last run | last seen |",
        "| --- | --- | ---: | ---: | --- | --- |",
    ]
    for signature in sorted(blockers):
        blocker = blockers[signature]
        lines.append(
            f"| `{_escape_cell(blocker.signature)}` "
            f"| {_escape_cell(blocker.example)} "
            f"| {blocker.runs} "
            f"| {blocker.occurrences} "
            f"| {blocker.last_run_id} "
            f"| {blocker.last_seen_at} |"
        )
    lines.append("")
    return "\n".join(lines)


def export_blocker_ledger(
    destination: Path,
    *,
    runs_dir: Path | None = None,
    existing: Path | None = None,
    limit: int = DEFAULT_SCAN_LIMIT,
) -> Path:
    """Write the ledger, folding local run evidence into the committed record.

    With no `runs_dir`, this reproduces `existing` exactly. That is what the
    staleness gate depends on, and why it can run on a clone.
    """

    previous: dict[str, ObservedBlocker] = {}
    previous_newest = ""
    if existing is not None and existing.is_file():
        previous, previous_newest = parse_ledger(_read_utf8(existing))

    discovered: dict[str, ObservedBlocker] = {}
    newest_run_id = previous_newest
    if runs_dir is not None:
        discovered, scanned_newest = blockers_from_runs(runs_dir, limit)
        if scanned_newest:
            newest_run_id = scanned_newest

    merged = merge_blockers(previous, discovered)
    destination.mkdir(parents=True, exist_ok=True)
    path = destination / LEDGER_NAME
    _write_utf8(path, render_ledger(merged, newest_run_id))
    return path
