from __future__ import annotations

from pathlib import Path

from .action_completeness import audit_action_completeness, render_action_queue
from .affordance_parity import audit_binding_parity
from .affordance_surfaces import render_surface_registry
from .affordances import AFFORDANCE_ADAPTERS
from .context_action_parity import (
    WITNESSES_PATH,
    load_witnesses,
    render_context_action_parity,
)
from .ui_affordances import audit

GENERATED_MARKER = "<!-- generated by scripts/export_docs.py; edits are overwritten -->"


def _affordance_catalog() -> str:
    """The planner surface, emitted from the adapters that generate it."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Affordance adapter catalog",
        "",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "| adapter | sources | private operations | denominator | completeness boundary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for adapter in AFFORDANCE_ADAPTERS:
        sources = ", ".join(f"`{source.value}`" for source in sorted(adapter.sources))
        operations = ", ".join(f"`{kind}`" for kind in sorted(adapter.operation_kinds))
        lines.append(
            f"| `{adapter.name}` | {sources} | {operations} | "
            f"{adapter.denominator} | {adapter.completeness_boundary} |"
        )
    lines.extend(
        [
            "",
            "The playing model sees runtime instances of this registry, not the",
            "private operation kinds in the table. Every selection is rebound",
            "against the same adapter before an operation is materialized.",
            "",
        ]
    )
    return "\n".join(lines)


def _affordance_surfaces() -> str:
    """Every surface a player acts through, examined or not."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Affordance surfaces",
        "",
        "Binding parity was captured, then widget parity, and the word",
        "\"parity\" quietly came to mean the thin interface shell those two",
        "cover. Kenshi's content database — larger than every captured surface",
        "combined — went unmentioned for a whole session because no artefact had",
        "a row for it. An absent surface reads exactly like a covered one.",
        "",
        "This inventory is hand-authored, and unavoidably so: nothing Kenshi",
        "ships enumerates its own surfaces. The defence is visibility, not",
        "automation. `unexamined` is printed beside `captured`, and a surface",
        "may not report a size it has not measured.",
        "",
        "```text",
    ]
    lines.extend(render_surface_registry())
    lines.extend(["```", ""])
    return "\n".join(lines)


def _game_binding_parity() -> str:
    """Game-enumerated bindings against real planner routes and decisions."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Game binding parity",
        "",
        "The denominator is a verbatim `controls.cfg` captured from Kenshi, not",
        "an action list maintained by this project. The suite also compares its",
        "binding names with the installed game whenever that file is available.",
        "Known missing entries are the implementation queue; new or unclassified",
        "entries fail the gate. This binding surface is one source adapter, not a",
        "claim that every widget or world interaction has been enumerated.",
        "",
        "```text",
    ]
    lines.extend(audit_binding_parity().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def _action_queue() -> str:
    """Every private operation against what its execution kind requires."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Private operation implementation queue",
        "",
        "Derived from each contract's own `ActionExecution`, so the checklist",
        "cannot drift from what execution requires: an atomic handler needs an",
        "executor branch, while an option-backed action gets its terminal from",
        "the option. These are runtime-private operations beneath the affordance",
        "adapters, not a second planner contract.",
        "",
        "An unfinished operation may not appear in an adapter. Stubs that pass are",
        "worse than gaps that fail: a generated completion returning nothing",
        "satisfies every structural check and verifies nothing.",
        "",
        "```text",
    ]
    lines.extend(render_action_queue(audit_action_completeness()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _modeled_interface_audit() -> str:
    """Navigation checks within already modeled interfaces, never a denominator."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Modeled interface audit",
        "",
        "This hand-written registry audits enter/navigate/interact/exit only for",
        "interfaces the project already models. It cannot discover a missing game",
        "surface and is not an affordance-parity denominator. Presence says a",
        "mechanism is declared, not that its effect is proven live.",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "```text",
    ]
    lines.extend(audit().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def export_docs(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    documents = {
        "AFFORDANCE_CATALOG.md": _affordance_catalog(),
        "AFFORDANCE_SURFACES.md": _affordance_surfaces(),
        "CONTEXT_ACTION_PARITY.md": render_context_action_parity(
            load_witnesses(WITNESSES_PATH)
        ),
        "GAME_BINDING_PARITY.md": _game_binding_parity(),
        "OPERATION_QUEUE.md": _action_queue(),
        "MODELED_INTERFACE_AUDIT.md": _modeled_interface_audit(),
    }
    paths: list[Path] = []
    for name, body in documents.items():
        path = output_dir / name
        path.write_text(body, encoding="utf-8")
        paths.append(path)
    return paths
