from __future__ import annotations

from pathlib import Path

from .action_contracts import ACTION_CONTRACTS
from .ui_affordances import audit

GENERATED_MARKER = "<!-- generated by scripts/export_docs.py; edits are overwritten -->"


def _action_catalog() -> str:
    """The action surface, emitted from the contracts the runtime actually routes.

    Hand-written copies of this table drifted from the code twice; the checked-in
    file is regenerated and a test fails when it is stale.
    """

    lines = [
        GENERATED_MARKER,
        "",
        "# Action catalog",
        "",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "| kind | version | planner-visible | execution | native | max primitives |"
        " capabilities |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for kind in sorted(ACTION_CONTRACTS):
        contract = ACTION_CONTRACTS[kind]
        capabilities = (
            ", ".join(f"`{name}`" for name in sorted(contract.required_capabilities))
            or "—"
        )
        lines.append(
            f"| `{kind}` | {contract.version}"
            f" | {'yes' if contract.planner_visible else 'no'}"
            f" | {contract.execution.value}"
            f" | {'yes' if contract.native_assisted else 'no'}"
            f" | {contract.max_primitive_actions}"
            f" | {capabilities} |"
        )
    lines.append("")
    return "\n".join(lines)


def _ui_affordance_coverage() -> str:
    """Kenshi's GUI surface against our catalog, from the offline audit itself.

    The hand-written version of this stated counts that had to be re-typed every
    time the catalog moved, so it was wrong more often than not.
    """

    lines = [
        GENERATED_MARKER,
        "",
        "# UI affordance coverage",
        "",
        "Presence audit only: it says a mechanism is declared, not that its effect",
        "is proven live. Regenerate with `python scripts/export_docs.py`.",
        "",
        "```text",
    ]
    lines.extend(audit().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def export_docs(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    documents = {
        "ACTION_CATALOG.md": _action_catalog(),
        "UI_AFFORDANCE_COVERAGE.md": _ui_affordance_coverage(),
    }
    paths: list[Path] = []
    for name, body in documents.items():
        path = output_dir / name
        path.write_text(body, encoding="utf-8")
        paths.append(path)
    return paths
