from __future__ import annotations

from pathlib import Path

from .action_completeness import audit_action_completeness, render_action_queue
from .action_contracts import ACTION_CONTRACTS
from .affordance_parity import audit_binding_parity
from .ui_affordances import audit

GENERATED_MARKER = "<!-- generated by scripts/export_docs.py; edits are overwritten -->"


def _action_catalog() -> str:
    """The action surface, emitted from the contracts the runtime actually routes.

    Hand-written copies of this table drifted from the code twice; the checked-in
    file is regenerated and a test fails when it is stale.
    """

    lines = [
        GENERATED_MARKER,
        "",
        "# Action catalog",
        "",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "| kind | version | planner-visible | execution | completion | native |"
        " max primitives | capabilities |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for kind in sorted(ACTION_CONTRACTS):
        contract = ACTION_CONTRACTS[kind]
        capabilities = (
            ", ".join(f"`{name}`" for name in sorted(contract.required_capabilities))
            or "—"
        )
        completion = (
            "controller terminal"
            if contract.controller_verified
            else (
                "runtime-derived"
                if contract.derive_completion_conditions is not None
                else "planner conditions"
            )
        )
        lines.append(
            f"| `{kind}` | {contract.version}"
            f" | {'yes' if contract.planner_visible else 'no'}"
            f" | {contract.execution.value}"
            f" | {completion}"
            f" | {'yes' if contract.native_assisted else 'no'}"
            f" | {contract.max_primitive_actions}"
            f" | {capabilities} |"
        )
    lines.extend(
        [
            "",
            "`runtime-derived` applies when that action variant exposes a "
            "deterministic signal;",
            "variants whose factory declines remain planner-owned and fail "
            "closed without a condition.",
            "",
        ]
    )
    return "\n".join(lines)


def _game_binding_parity() -> str:
    """Game-enumerated bindings against real planner routes and decisions."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Game binding parity",
        "",
        "The denominator is a verbatim `controls.cfg` captured from Kenshi, not",
        "an action list maintained by this project. The suite also compares its",
        "binding names with the installed game whenever that file is available.",
        "Known missing entries are the implementation queue; new or unclassified",
        "entries fail the gate. This binding surface is one source adapter, not a",
        "claim that every widget or world interaction has been enumerated.",
        "",
        "```text",
    ]
    lines.extend(audit_binding_parity().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def _action_queue() -> str:
    """Every contracted action against what its execution kind requires."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Action implementation queue",
        "",
        "Derived from each contract's own `ActionExecution`, so the checklist",
        "cannot drift from what the code requires: an atomic handler needs an",
        "executor branch, while an option-backed action gets its terminal from",
        "the option. Adding an action touches a model, two unions, a contract, a",
        "bind, a completion owner, an executor branch and two generated",
        "artefacts; nobody holds that list, so a missing piece used to surface as",
        "a plan rejected mid-run.",
        "",
        "An unfinished action may not be planner-visible. Stubs that pass are",
        "worse than gaps that fail: a generated completion returning nothing",
        "satisfies every structural check and verifies nothing.",
        "",
        "```text",
    ]
    lines.extend(render_action_queue(audit_action_completeness()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _modeled_interface_audit() -> str:
    """Navigation checks within already modeled interfaces, never a denominator."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Modeled interface audit",
        "",
        "This hand-written registry audits enter/navigate/interact/exit only for",
        "interfaces the project already models. It cannot discover a missing game",
        "surface and is not an affordance-parity denominator. Presence says a",
        "mechanism is declared, not that its effect is proven live.",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "```text",
    ]
    lines.extend(audit().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def export_docs(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    documents = {
        "ACTION_CATALOG.md": _action_catalog(),
        "GAME_BINDING_PARITY.md": _game_binding_parity(),
        "ACTION_QUEUE.md": _action_queue(),
        "MODELED_INTERFACE_AUDIT.md": _modeled_interface_audit(),
    }
    paths: list[Path] = []
    for name, body in documents.items():
        path = output_dir / name
        path.write_text(body, encoding="utf-8")
        paths.append(path)
    return paths
