"""One committed record of which mutation campaigns still describe the code.

`runs/mutation/*.json` is the evidence a campaign produces, and `.gitignore`
excludes `runs/*`: run artifacts are machine-local by design. That left the
repository asserting mutation coverage in prose while the numbers behind the
claim lived on one laptop, and left every artifact silent about *which* tree it
attested — a 429/429 result and a 429/429 result taken four commits apart are
indistinguishable in the file that records them.

So each artifact now records the digest of its module's source, and this module
renders one generated document from those artifacts. `state` is *derived* when
the document is written, by digesting each module again and comparing: a module
edited after its campaign reports `source-changed` whether or not anyone
remembered to look. Storing the state instead would make the gate vacuous.

The consequence worth keeping: because every input is committed — the ledger and
the sources it digests — regenerating on a clone with no artifacts at all
reproduces the same file. The staleness gate reads no machine-local state.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from .mutation_campaign import MutationBatch, discover_mutation_batches

GENERATED_MARKER = (
    "<!-- generated by scripts/export_mutation_ledger.py; edits are overwritten -->"
)
LEDGER_NAME = "MUTATION_ATTESTATION.md"

# Enough of the digest to make an accidental collision impossible and a
# deliberate one pointless, while leaving the table readable. The full digest
# buys nothing here: this detects edits, it does not resist an adversary who
# can already write to the ledger.
DIGEST_LENGTH = 16

ATTESTED = "attested"
SOURCE_CHANGED = "source-changed"
UNVERIFIED = "unverified"
NEVER = "never"

_ABSENT = "—"
_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
_COLUMNS = 7


# A UTF-8 text file is a UTF-8 text file. Every caller's parsed content is tested;
# codec aliases are equivalent and only obscure the behavioral survivors.
# pragma: no mutate start
def _read_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_utf8(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


# pragma: no mutate end


@dataclass(frozen=True, slots=True)
class Attestation:
    """One campaign's surviving evidence for one shard. Data only (I23)."""

    shard: str
    mutants: int
    killed: int
    open_mutants: int
    attested_at: str
    source_digest: str


def source_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:DIGEST_LENGTH]


def sources_are_instrumented(repo_root: Path) -> bool:
    """Whether `repo_root` holds mutmut's rewritten sources instead of the checkout.

    mutmut copies the tree into `<workspace>/mutants/` and rewrites every module
    into its `x_*__mutmut_N` variants. Digests taken there describe generated
    instrumentation, so every comparison against a committed digest reports
    `source-changed` — including for the shard being measured, which then refuses
    its own campaign before a single mutant runs.

    Gates that compare *behavior* are unaffected: they regenerate from whatever
    code is loaded, and an inactive mutant produces an identical file. Only
    byte-level comparison is vacuous here, and it should say so rather than fail.
    """

    return repo_root.name == "mutants"


def normalize_timestamp(value: str) -> str:
    """Second-resolution UTC, so rendering and parsing are exact inverses."""

    return datetime.fromisoformat(value).astimezone(UTC).strftime(_TIMESTAMP_FORMAT)


def attestation_state(attestation: Attestation | None, current_digest: str) -> str:
    if attestation is None:
        return NEVER
    if not attestation.source_digest:
        return UNVERIFIED
    if attestation.source_digest == current_digest:
        return ATTESTED
    return SOURCE_CHANGED


def attestation_from_artifact(payload: object) -> Attestation | None:
    """One artifact as evidence, or `None` when it proves nothing.

    A zero-mutant run is not a weak attestation, it is the absence of one:
    `mutation_campaign.mutation_exit_code` already fails closed on it. Ranking
    it as the newest result for a shard would let a cache invalidation erase a
    real campaign from the record.
    """

    if not isinstance(payload, dict):
        return None
    shard = payload.get("batch")
    total = payload.get("total")
    actionable = payload.get("actionable_mutants")
    completed_at = payload.get("completed_at")
    if not isinstance(shard, str) or not isinstance(total, int):
        return None
    if not isinstance(actionable, list) or not isinstance(completed_at, str):
        return None
    if total <= 0:
        return None
    digest = payload.get("source_sha256")
    return Attestation(
        shard=shard,
        mutants=total,
        killed=total - len(actionable),
        open_mutants=len(actionable),
        attested_at=normalize_timestamp(completed_at),
        source_digest=digest[:DIGEST_LENGTH] if isinstance(digest, str) else "",
    )


def attestations_from_artifacts(artifact_dir: Path) -> dict[str, Attestation]:
    """The latest usable campaign per shard, over every artifact on this machine."""

    latest: dict[str, Attestation] = {}
    for path in sorted(artifact_dir.glob("*.json")):
        try:
            payload = json.loads(_read_utf8(path))
        except (OSError, json.JSONDecodeError):
            continue
        attestation = attestation_from_artifact(payload)
        if attestation is None:
            continue
        previous = latest.get(attestation.shard)
        if previous is None or attestation.attested_at >= previous.attested_at:
            latest[attestation.shard] = attestation
    return latest


def merge_attestations(
    existing: dict[str, Attestation],
    discovered: dict[str, Attestation],
) -> dict[str, Attestation]:
    """Later evidence wins; the committed record is never silently downgraded."""

    merged = dict(existing)
    for shard, attestation in discovered.items():
        previous = merged.get(shard)
        if previous is None or attestation.attested_at >= previous.attested_at:
            merged[shard] = attestation
    return merged


def parse_ledger(text: str) -> dict[str, Attestation]:
    """Read back a rendered ledger. The exact inverse of `render_ledger`."""

    attestations: dict[str, Attestation] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or not stripped.endswith("|"):
            continue
        fields = [field.strip() for field in stripped[1:-1].split("|")]
        if len(fields) != _COLUMNS:
            continue
        shard = fields[0]
        if not shard.startswith("`") or not shard.endswith("`"):
            continue
        if fields[6] == NEVER:
            continue
        attestations[shard[1:-1]] = Attestation(
            shard=shard[1:-1],
            mutants=int(fields[1]),
            killed=int(fields[2]),
            open_mutants=int(fields[3]),
            attested_at=fields[4],
            source_digest="" if fields[5] == _ABSENT else fields[5],
        )
    return attestations


def _row(shard: str, attestation: Attestation | None, state: str) -> str:
    if attestation is None:
        cells = [_ABSENT] * 5
    else:
        cells = [
            str(attestation.mutants),
            str(attestation.killed),
            str(attestation.open_mutants),
            attestation.attested_at,
            attestation.source_digest or _ABSENT,
        ]
    return f"| `{shard}` | " + " | ".join(cells) + f" | {state} |"


def render_ledger(
    attestations: dict[str, Attestation],
    batches: dict[str, MutationBatch],
    repo_root: Path,
) -> str:
    """The document. Shards come from discovery, so a deleted module drops out."""

    states: dict[str, str] = {}
    rows: list[str] = []
    for shard in sorted(batches):
        attestation = attestations.get(shard)
        digest = source_digest(repo_root / batches[shard].source_path)
        state = attestation_state(attestation, digest)
        states[shard] = state
        rows.append(_row(shard, attestation, state))

    tally = {
        name: sum(1 for state in states.values() if state == name)
        for name in (ATTESTED, SOURCE_CHANGED, UNVERIFIED, NEVER)
    }
    open_mutants = sum(
        attestation.open_mutants
        for shard, attestation in attestations.items()
        if states.get(shard) in {ATTESTED, UNVERIFIED}
    )
    lines = [
        GENERATED_MARKER,
        "",
        "# Mutation attestation",
        "",
        "Which mutation campaigns still describe the code in this checkout.",
        "Regenerate with `python scripts/export_mutation_ledger.py`. It reads",
        "`runs/mutation/`, which is machine-local and deliberately not committed —",
        "this file is the committed record of what those artifacts said.",
        "",
        "`killed` counts mutants a campaign accounted for; `open` counts the rest,",
        "and a shard is finished only at zero. `state` is recomputed every time this",
        "file is written, by digesting each module and comparing it against the",
        "digest recorded when its campaign ran:",
        "",
        f"- `{ATTESTED}` — a campaign ran and the module is byte-identical since.",
        f"- `{SOURCE_CHANGED}` — the module was edited afterwards, so these numbers",
        "  no longer describe the code that ships.",
        f"- `{UNVERIFIED}` — the campaign predates source digests in artifacts; the",
        "  tree it attested is unknown. Re-running the shard replaces this.",
        f"- `{NEVER}` — no campaign has ever been recorded for this module.",
        "",
        f"`{ATTESTED}` does not promise the numbers would reproduce: a mutation result",
        "also depends on the tests, and a changed test suite is not tracked here. It",
        "promises only that the module under test has not moved.",
        "",
        f"{len(batches)} shards: {tally[ATTESTED]} {ATTESTED},"
        f" {tally[UNVERIFIED]} {UNVERIFIED}, {tally[SOURCE_CHANGED]} {SOURCE_CHANGED},"
        f" {tally[NEVER]} {NEVER}; {open_mutants} open"
        f" {'mutant' if open_mutants == 1 else 'mutants'} where the numbers still apply.",
        "",
        "| shard | mutants | killed | open | attested | source | state |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(rows)
    lines.append("")
    return "\n".join(lines)


def export_mutation_ledger(
    output_dir: Path,
    *,
    repo_root: Path,
    existing: Path | None = None,
    artifact_dir: Path | None = None,
) -> Path:
    """Render the ledger, carrying `existing` forward and folding in artifacts.

    With `artifact_dir` unset this is the staleness gate's view: committed
    evidence re-checked against the committed tree, and nothing else.
    """

    batches = discover_mutation_batches(repo_root / "src" / "kenshi_agent")
    attestations: dict[str, Attestation] = {}
    if existing is not None and existing.exists():
        attestations = parse_ledger(_read_utf8(existing))
    if artifact_dir is not None and artifact_dir.is_dir():
        attestations = merge_attestations(
            attestations,
            attestations_from_artifacts(artifact_dir),
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / LEDGER_NAME
    _write_utf8(path, render_ledger(attestations, batches, repo_root))
    return path
