from __future__ import annotations

from pathlib import Path

from ..affordances import AFFORDANCE_ADAPTERS
from .affordance_parity import audit_binding_parity
from .affordance_surfaces import render_surface_registry
from .context_action_parity import (
    WITNESSES_PATH,
    load_witnesses,
    render_context_action_parity,
)
from .coverage_frontier import assess_coverage_frontier, render_coverage_frontier
from .gui_coverage import assess_gui_coverage, render_gui_coverage
from .interaction_catalog import (
    audit_interaction_catalog,
    render_interaction_catalog,
)
from .operation_registry_audit import (
    audit_operation_registry,
    render_operation_registry_report,
)
from .reporting_surface import assess_reporting_surface, render_reporting_surface
from .ui_affordances import audit

GENERATED_MARKER = "<!-- generated by scripts/export_docs.py; edits are overwritten -->"


def _affordance_catalog() -> str:
    """The planner surface, emitted from the adapters that generate it."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Affordance adapter catalog",
        "",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "| adapter | sources | private operations | denominator | completeness boundary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for adapter in AFFORDANCE_ADAPTERS:
        sources = ", ".join(f"`{source.value}`" for source in sorted(adapter.sources))
        operations = ", ".join(f"`{kind}`" for kind in sorted(adapter.operation_kinds))
        lines.append(
            f"| `{adapter.name}` | {sources} | {operations} | "
            f"{adapter.denominator} | {adapter.completeness_boundary} |"
        )
    lines.extend(
        [
            "",
            "The playing model sees runtime instances of this registry, not the",
            "private operation kinds in the table. Every selection is rebound",
            "against the same adapter before an operation is materialized.",
            "",
        ]
    )
    return "\n".join(lines)


def _affordance_surfaces() -> str:
    """Every surface a player acts through, examined or not."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Affordance surfaces",
        "",
        "Binding parity was captured, then widget parity, and the word",
        "\"parity\" quietly came to mean the thin interface shell those two",
        "cover. Kenshi's content database — larger than every captured surface",
        "combined — went unmentioned for a whole session because no artefact had",
        "a row for it. An absent surface reads exactly like a covered one.",
        "",
        "This inventory is hand-authored, and unavoidably so: nothing Kenshi",
        "ships enumerates its own surfaces. The defence is visibility, not",
        "automation. `unexamined` is printed beside `captured`, and a surface",
        "may not report a size it has not measured.",
        "",
        "```text",
    ]
    lines.extend(render_surface_registry())
    lines.extend(["```", ""])
    return "\n".join(lines)


def _game_binding_parity() -> str:
    """Game-enumerated bindings against real planner routes and decisions."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Game binding parity",
        "",
        "The denominator is a verbatim `controls.cfg` captured from Kenshi, not",
        "an action list maintained by this project. The suite also compares its",
        "binding names with the installed game whenever that file is available.",
        "Known missing entries are the implementation queue; new or unclassified",
        "entries fail the gate. This binding surface is one source adapter, not a",
        "claim that every widget or world interaction has been enumerated.",
        "",
        "```text",
    ]
    lines.extend(audit_binding_parity().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def _operation_definitions() -> str:
    """Prove private operation ownership from the sole registry."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Private operation definitions",
        "",
        "Derived from the sole operation-definition registry and the affordance",
        "adapters that emit selections. The report proves that every emitted",
        "operation has one definition and handler identity, definitions are not",
        "duplicated, and every adapter retains a source-specific completeness",
        "boundary.",
        "",
        "Internal-only definitions are controller phases or runtime operations;",
        "they still bind through this registry but are not planner-visible offers.",
        "",
        "```text",
    ]
    lines.extend(render_operation_registry_report(audit_operation_registry()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _interaction_catalog() -> str:
    """How each operation addresses Kenshi, and how much of that is proven."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Interaction catalog",
        "",
        "Slice 0 inventory for the interaction-scope and order-lifecycle stage.",
        "",
        "The first table is derived from the sole operation registry and states",
        "only what the code says today, including the `SelectionRequirement`",
        "this stage exists to delete. The second table is the hand-authored",
        "proposal in `docs/reconstruction/interaction_proof_status.json`, kept",
        "separate so the proposal and the implementation cannot silently",
        "converge. Slice 1 moves the proposed contract into the registry, after",
        "which the manifest may carry only proof status and evidence.",
        "",
        "Neither table is an authority over Kenshi's behavior. `unproven` is the",
        "honest majority: no group-scope behavior is live-proven anywhere in this",
        "repository, and every captured context-menu witness had exactly one",
        "character selected.",
        "",
        "```text",
    ]
    lines.extend(render_interaction_catalog(audit_interaction_catalog()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _reporting_surface() -> str:
    """Which post-mortem questions a real run bundle can answer."""

    from pathlib import Path as _Path

    root = _Path(__file__).resolve().parents[3]
    bundles = sorted(
        (path for path in (root / "runs").glob("*/events.jsonl")),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    lines = [
        GENERATED_MARKER,
        "",
        "# Run bundle reporting surface",
        "",
        "A run bundle is the only durable account of what happened. Whether it",
        "is a good one is not a matter of size - these bundles are large - but",
        "of which questions survive into it.",
        "",
        "Every question below was actually asked of a bundle during",
        "development. The status is derived by inspecting the most recent real",
        "bundle, not asserted, so a gap closes here only when the evidence",
        "genuinely appears.",
        "",
        "```text",
    ]
    if not bundles:
        lines.append("no run bundles present")
    else:
        lines.extend(render_reporting_surface(assess_reporting_surface(bundles[0])))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _gui_coverage() -> str:
    """Kenshi's declared interface beside what the project models."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Declared GUI coverage",
        "",
        "Kenshi ships every window it can draw as MyGUI layout XML in",
        "`data/gui/layout`. That is the game's own enumeration of its",
        "interface, so it is the denominator - the same role `controls.cfg`",
        "plays for bindings and `TaskType.h` for orders.",
        "",
        "Captured structurally in `game_sources/kenshi/gui_layouts.json`: the",
        "widget tree, each part's name and type, and its authored caption.",
        "Those captions are placeholders (`Day: 12345`, `Unobtainium`), useful",
        "for identifying a widget's role and never as expected text.",
        "",
        "```text",
    ]
    lines.extend(render_gui_coverage(assess_gui_coverage()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _coverage_frontier() -> str:
    """Why the world-target surface is the size it is, derived from source."""

    lines = [
        GENERATED_MARKER,
        "",
        "# World-target coverage frontier",
        "",
        "The binding surface has a source-derived denominator (`controls.cfg`)",
        "and the order vocabulary has one (`TaskType.h`). The world-target",
        "surface has neither: the plug-in emits fixed context-action literals",
        "instead of asking Kenshi what a target affords.",
        "",
        "That makes coverage a property of the exporter rather than of",
        "exploration. Three wired pairs is not a young witness set that more",
        "runs would grow; it is the ceiling. This report derives that ceiling",
        "from the native source, so it stops being true as soon as the",
        "hardcoding does.",
        "",
        "```text",
    ]
    lines.extend(render_coverage_frontier(assess_coverage_frontier()))
    lines.extend(["```", ""])
    return "\n".join(lines)


def _modeled_interface_audit() -> str:
    """Navigation checks within already modeled interfaces, never a denominator."""

    lines = [
        GENERATED_MARKER,
        "",
        "# Modeled interface audit",
        "",
        "This hand-written registry audits enter/navigate/interact/exit only for",
        "interfaces the project already models. It cannot discover a missing game",
        "surface and is not an affordance-parity denominator. Presence says a",
        "mechanism is declared, not that its effect is proven live.",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "```text",
    ]
    lines.extend(audit().as_lines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def export_docs(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    documents = {
        "AFFORDANCE_CATALOG.md": _affordance_catalog(),
        "AFFORDANCE_SURFACES.md": _affordance_surfaces(),
        "CONTEXT_ACTION_PARITY.md": render_context_action_parity(
            load_witnesses(WITNESSES_PATH)
        ),
        "COVERAGE_FRONTIER.md": _coverage_frontier(),
        "GUI_COVERAGE.md": _gui_coverage(),
        "REPORTING_SURFACE.md": _reporting_surface(),
        "GAME_BINDING_PARITY.md": _game_binding_parity(),
        "INTERACTION_CATALOG.md": _interaction_catalog(),
        "OPERATION_DEFINITIONS.md": _operation_definitions(),
        "MODELED_INTERFACE_AUDIT.md": _modeled_interface_audit(),
    }
    paths: list[Path] = []
    for name, body in documents.items():
        path = output_dir / name
        path.write_text(body, encoding="utf-8")
        paths.append(path)
    return paths
