"""Generated reference for the Protocol 2.0 world-model schema."""

from __future__ import annotations

from ..core.protocol_2 import Protocol2WorldModel


def render_protocol_2_world_model() -> str:
    """Render names and strictness from the Pydantic schema authority."""

    schema = Protocol2WorldModel.model_json_schema()
    properties = schema["properties"]
    required = set(schema["required"])
    lines = [
        "<!-- generated by scripts/export_docs.py; edits are overwritten -->",
        "",
        "# Protocol 2.0 world-model schema",
        "",
        "Regenerate with `python scripts/export_docs.py`.",
        "",
        "`Protocol2WorldModel` in `src/kenshi_agent/core/protocol_2.py` is the",
        "typed authority. This is the accepted producer target, not a claim that",
        "the current 1.x native producer emits it yet.",
        "",
        "| root field | required |",
        "| --- | --- |",
    ]
    for name in properties:
        lines.append(f"| `{name}` | {'yes' if name in required else 'no'} |")
    definitions = sorted(schema.get("$defs", {}))
    lines.extend(
        [
            "",
            "Strict model definitions:",
            "",
            *[f"- `{name}`" for name in definitions],
            "",
            "Rejected compatibility names:",
            "",
            "- `squad`",
            "- `active_command_id`",
            "",
            "All object schemas forbid additional properties. Every bounded",
            "collection carries `completeness` (`complete` or `truncated`) and",
            "an exact `known_total` when the source can know it. A null total on",
            "a truncated collection means unknown, never zero or retained count.",
            "",
        ]
    )
    return "\n".join(lines)
